class Executor:
    def __init__(self, tool_registry):
        self.tools = tool_registry

    def run(self, plan: dict, user_query: str):
        """Get the plan and execute the tools in sequence according to the plan
        args:
            plan: dict (plan generated by the planner in planner.py)
            user_query: str (user query)
        """
        state = {
            "query": user_query,
            "expanded_queries": None,
            "retrieved_chunks": None,
            "reranked_chunks": None,
            "answer": None
        }

        for action in plan["actions"]:
            tool = action["tool"]
            args = action.get("args", {})

            if tool == "retrieve":
                self.tools.retrieve(state, **args)

            elif tool == "rerank":
                self.tools.rerank(state)

            elif tool == "answer":
                self.tools.answer(state)

            else:
                raise ValueError(f"Unknown tool: {tool}")

        return state["answer"]
